name: "Documentation"
title: "📚 Documentation"
description: "Documentation issue"
labels: ["type: docs"]

body:
  - type: textarea
    id: description
    attributes:
      label: What needs work?
      placeholder: Describe the documentation issue.
    validations:
      required: true
