__version__ = "0.0.4"
__status__ = "Development"
__authors__ = ["Douglas Myers-Turnbull"]
__credits__ = ["Douglas Myers-Turnbull"]
__maintainer__ = "Douglas Myers-Turnbull"
__copyright__ = "Copyright 2020"
__license__ = "Apache-2.0"
__date__ = "2020-04-29"
__contact__ = "Douglas Myers-Turnbull"
