# https://stackoverflow.com/questions/53835198/integrating-python-poetry-with-docker/54763270#54763270

FROM python:3.9

# See https://github.com/opencontainers/image-spec/blob/master/annotations.md
LABEL name="$${project}" \
      version="$${version}" \
      vendor="$${user}" \
      org.opencontainers.image.title="$${project}" \
      org.opencontainers.image.version="$${version}" \
      org.opencontainers.image.url="https://github.com/$${user}/$${project}" \
      org.opencontainers.image.documentation="https://github.com/$${user}/$${project}"

ARG YOUR_ENV

ENV YOUR_ENV=${YOUR_ENV} \
    PYTHONFAULTHANDLER=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONHASHSEED=random \
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=120 \
    POETRY_VERSION=1.1.4

# System deps:
RUN pip install "poetry==$POETRY_VERSION"

# Copy only requirements to cache them in docker layer
WORKDIR /code
COPY poetry.lock pyproject.toml /code/

# Project initialization:
RUN poetry config virtualenvs.create false \
  && poetry install $(test "$YOUR_ENV" == production && echo "--no-dev") --no-interaction --no-ansi

# Creating folders, and files for a project:
COPY . /code
